version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest test_calculator.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes