version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre-build:
    commands:
      - echo "start prebuild and end it"

  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest test_calculator.py

  post-build:
    commands:
      - echo "Build completed successfully"



artifacts:
  files:
    - '**/*'
  base-directory: .

reports:
  pytest_reports:
    files:
      - "reports/result.xml"
    discard-paths: yes